#!/usr/bin/env python3
"""
Compare PPTX files generated by python-pptx and ppt-rs.
Extracts and compares XML structure, metadata, and content.
"""

import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path
import difflib
import sys
import os

def extract_pptx_contents(pptx_path):
    """Extract all XML files from PPTX."""
    contents = {}
    try:
        with zipfile.ZipFile(pptx_path, 'r') as z:
            for name in z.namelist():
                if name.endswith('.xml') or name.endswith('.rels'):
                    try:
                        contents[name] = z.read(name).decode('utf-8')
                    except:
                        # Skip binary files
                        pass
    except Exception as e:
        print(f"Error extracting {pptx_path}: {e}")
    return contents

def normalize_xml(xml_string):
    """Normalize XML for comparison by removing whitespace differences."""
    try:
        root = ET.fromstring(xml_string)
        # Remove all text content (whitespace)
        for elem in root.iter():
            if elem.text:
                elem.text = elem.text.strip() if elem.text else None
            if elem.tail:
                elem.tail = elem.tail.strip() if elem.tail else None
        return ET.tostring(root, encoding='unicode')
    except:
        return xml_string

def compare_files(file1_path, file2_path):
    """Compare two PPTX files."""
    print(f"\n{'='*80}")
    print(f"Comparing PPTX Files")
    print(f"{'='*80}")
    print(f"File 1 (Reference): {file1_path}")
    print(f"File 2 (ppt-rs):    {file2_path}")
    
    if not os.path.exists(file1_path):
        print(f"Error: File 1 not found: {file1_path}")
        return False
    
    if not os.path.exists(file2_path):
        print(f"Error: File 2 not found: {file2_path}")
        return False
    
    # Extract contents
    print("\nExtracting XML files...")
    contents1 = extract_pptx_contents(file1_path)
    contents2 = extract_pptx_contents(file2_path)
    
    print(f"  File 1: {len(contents1)} XML files")
    print(f"  File 2: {len(contents2)} XML files")
    
    # Get all unique files
    all_files = set(contents1.keys()) | set(contents2.keys())
    
    # Compare each file
    differences = {}
    matches = 0
    
    for filename in sorted(all_files):
        xml1 = contents1.get(filename, "")
        xml2 = contents2.get(filename, "")
        
        if xml1 == xml2:
            matches += 1
        else:
            differences[filename] = (xml1, xml2)
    
    # Report results
    print(f"\n{'='*80}")
    print(f"Comparison Results")
    print(f"{'='*80}")
    print(f"Total XML files: {len(all_files)}")
    print(f"Matching files: {matches}")
    print(f"Different files: {len(differences)}")
    
    if differences:
        print(f"\n{'='*80}")
        print(f"Files with Differences")
        print(f"{'='*80}")
        
        for filename in sorted(differences.keys()):
            xml1, xml2 = differences[filename]
            print(f"\n--- {filename} ---")
            
            if not xml1:
                print("  Status: MISSING in File 1 (python-pptx)")
            elif not xml2:
                print("  Status: MISSING in File 2 (ppt-rs)")
            else:
                # Show line-by-line diff
                lines1 = xml1.splitlines(keepends=True)
                lines2 = xml2.splitlines(keepends=True)
                diff = difflib.unified_diff(lines1, lines2, lineterm='', n=2)
                diff_lines = list(diff)
                
                if diff_lines:
                    print(f"  Differences ({len(diff_lines)} lines):")
                    for i, line in enumerate(diff_lines[:30]):  # Show first 30 lines
                        print(f"    {line.rstrip()}")
                    if len(diff_lines) > 30:
                        print(f"    ... and {len(diff_lines) - 30} more lines")
    else:
        print("\n✓ All XML files match perfectly!")
    
    # Check file sizes
    print(f"\n{'='*80}")
    print(f"File Sizes")
    print(f"{'='*80}")
    size1 = os.path.getsize(file1_path)
    size2 = os.path.getsize(file2_path)
    diff = abs(size1 - size2)
    percent = (diff / max(size1, size2)) * 100 if max(size1, size2) > 0 else 0
    
    print(f"File 1: {size1:,} bytes")
    print(f"File 2: {size2:,} bytes")
    print(f"Difference: {diff:,} bytes ({percent:.1f}%)")
    
    # Calculate alignment score
    if len(all_files) > 0:
        score = (matches / len(all_files)) * 100
        print(f"\n{'='*80}")
        print(f"Alignment Score: {score:.1f}%")
        print(f"{'='*80}")
        
        if score >= 95:
            print("✓ EXCELLENT alignment")
        elif score >= 85:
            print("⚠ GOOD alignment (minor differences expected)")
        else:
            print("✗ POOR alignment (significant differences)")
        
        return score >= 85
    else:
        return False

def main():
    """Main comparison function."""
    # Default file paths
    file1 = "examples/output/reference_python_pptx.pptx"
    file2 = "examples/output/alignment_test_ppt_rs.pptx"
    
    # Allow command-line override
    if len(sys.argv) >= 3:
        file1 = sys.argv[1]
        file2 = sys.argv[2]
    elif len(sys.argv) == 2:
        print("Usage: compare_pptx.py [reference_file] [ppt_rs_file]")
        print(f"Using defaults: {file1} vs {file2}")
    
    success = compare_files(file1, file2)
    sys.exit(0 if success else 1)

if __name__ == "__main__":
    main()

